name: roles_screen
description: "A new Flutter package project."
version: 1.0.0+1
resolution: workspace
publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  architecture:
    path: ../../core/architecture
  domain:
    path: ../../core/domain
  app_localization:
    path: ../../core/app_localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
