name: myspygame
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

workspace:
  - packages/features/roles_screen
  - packages/core/app_localization
  - packages/core/architecture
  - packages/core/domain

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  app_localization:
    path: packages/core/app_localization
  architecture:
    path: packages/core/architecture
  domain:
    path: packages/core/domain
  roles_screen:
    path: packages/features/roles_screen

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  generate: true