name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.9.2"
          channel: "stable"

      - name: Install Dependencies
        run: make get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project
        run: make analyze

      - name: Run tests
        run: make test
